/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * Get current agent context
         * @description Returns authenticated agent info, active client, accessible branches, and client list
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * List agents with identities
         * @description Returns agents and linked identities (e.g., telegram)
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{agent_id}/telegram/link": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path: {
                /** @example f0b1a4c7-8f33-4f92-9b1f-9fe0f3d3e7b1 */
                agent_id: components["parameters"]["agent_id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Telegram linking token
         * @description Returns a short token and deep-link for Telegram account linking.
         */
        post: operations["linkAgentTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /**
         * List cases (Inbox)
         * @description Cursor-paginated list of handover cases with filters
         */
        get: operations["listCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** Get case details */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/take": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take ownership of a case
         * @description Assigns case to current agent. Returns 409 if already taken.
         *     Idempotent via Idempotency-Key header.
         */
        post: operations["takeCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/resolve": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve and close a case
         * @description Marks case as resolved. Must be assigned to current agent or owner/admin.
         */
        post: operations["resolveCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/return": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Return case to bot
         * @description Returns case to bot and closes the handover.
         */
        post: operations["returnCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/messages": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** Get messages for a case */
        get: operations["getCaseMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send message from manager to customer
         * @description Sends via outbox → WhatsApp. Case must be active and assigned.
         *     Idempotent via Idempotency-Key header.
         */
        post: operations["sendManagerMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** System health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/daily": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** Daily case metrics */
        get: operations["getMetricsDaily"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/health": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** Telegram connector health */
        get: operations["getTelegramHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/verify": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send verification message to Telegram */
        post: operations["verifyTelegramConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/test": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send test message to Telegram */
        post: operations["sendTelegramTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** Get client settings */
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update client settings
         * @description Owner/admin only
         */
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        /** List audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Machine-readable error code */
            code: string;
            /** @description Human-readable message */
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
            /** @description Correlation ID for debugging */
            trace_id: string;
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        ValidationErrorItem: {
            [key: string]: unknown;
        };
        ValidationError: {
            detail: components["schemas"]["ValidationErrorItem"][];
        };
        Agent: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "manager" | "support";
            /** Format: uuid */
            client_id?: string;
            /** Format: uuid */
            branch_id?: string | null;
            is_active?: boolean;
        };
        AgentIdentity: {
            /** @enum {string} */
            channel?: "telegram";
            external_id?: string;
            username?: string | null;
            /** Format: date-time */
            linked_at?: string | null;
        };
        AgentWithIdentities: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** @enum {string} */
            role?: "owner" | "admin" | "manager" | "support";
            /** Format: uuid */
            client_id?: string;
            /** Format: uuid */
            branch_id?: string | null;
            is_active?: boolean;
            identities?: components["schemas"]["AgentIdentity"][];
        };
        Client: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            /** Format: uuid */
            company_id?: string | null;
        };
        Branch: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            is_active?: boolean;
            instance_id?: string | null;
            telegram_chat_id?: string | null;
        };
        MeResponse: {
            agent?: components["schemas"]["Agent"];
            client?: components["schemas"]["Client"];
            branches?: components["schemas"]["Branch"][];
            clients?: components["schemas"]["Client"][];
            selection_required?: boolean;
            branch_selection_required?: boolean;
            /** Format: uuid */
            selected_branch_id?: string | null;
        };
        Case: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            conversation_id?: string;
            /** @enum {string} */
            status?: "pending" | "active" | "resolved";
            trigger_type?: string;
            trigger_value?: string | null;
            context_summary?: string | null;
            user_message?: string | null;
            assigned_to_name?: string | null;
            /** Format: uuid */
            branch_id?: string | null;
            /** @enum {string|null} */
            channel?: "whatsapp" | "telegram" | null;
            /** Format: date-time */
            created_at?: string;
            /** @enum {string} */
            sla_status?: "ok" | "warning" | "breached";
            customer_name?: string | null;
            customer_phone?: string | null;
            customer_remote_jid?: string | null;
            decision_trace?: Record<string, never>[] | null;
            telegram_trail?: components["schemas"]["TelegramTrail"];
        };
        CaseListResponse: {
            items?: components["schemas"]["Case"][];
            cursor?: string | null;
            has_more?: boolean;
        };
        CaseActionResponse: {
            success?: boolean;
            case?: components["schemas"]["Case"];
            sync?: components["schemas"]["CaseActionSync"];
        };
        CaseActionSync: {
            telegram?: components["schemas"]["SyncStatus"];
            client_notify?: components["schemas"]["SyncStatus"];
        };
        SyncStatus: {
            /** @enum {string} */
            status?: "ok" | "skipped" | "failed";
            detail?: string | null;
        };
        AgentListResponse: {
            items?: components["schemas"]["AgentWithIdentities"][];
        };
        Message: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            role?: "user" | "assistant" | "manager" | "system";
            content?: string;
            /** Format: date-time */
            created_at?: string;
            metadata?: Record<string, never> | null;
        };
        MessageListResponse: {
            items?: components["schemas"]["Message"][];
            cursor?: string | null;
            has_more?: boolean;
        };
        SendMessageRequest: {
            content: string;
        };
        SendMessageResponse: {
            success?: boolean;
            message?: components["schemas"]["Message"];
        };
        HealthResponse: {
            /** @enum {string} */
            status?: "ok" | "healthy" | "degraded" | "unhealthy";
            version?: string;
            /** @enum {string} */
            database?: "ok" | "error" | "connected";
            /** @enum {string} */
            redis?: "ok" | "error" | "connected";
            outbox_backlog?: number;
        };
        MetricsDailyResponse: {
            /** Format: date */
            date?: string;
            total_cases?: number;
            pending_cases?: number;
            active_cases?: number;
            resolved_cases?: number;
            avg_resolution_hours?: number | null;
        };
        BotConfig: {
            reminder_timeout_1?: number | null;
            reminder_timeout_2?: number | null;
            auto_close_timeout?: number | null;
            quiet_hours_enabled?: boolean;
            quiet_hours_start?: string | null;
            quiet_hours_end?: string | null;
            tone?: string | null;
            autolearn_enabled?: boolean;
            booking_enabled?: boolean;
            enable_reminders?: boolean;
            enable_owner_escalation?: boolean;
        };
        SettingsResponse: {
            branches?: components["schemas"]["Branch"][];
            agents?: components["schemas"]["Agent"][];
            bot_config?: components["schemas"]["BotConfig"];
        };
        SettingsUpdateRequest: {
            reminder_1_minutes?: number;
            reminder_2_minutes?: number;
            escalation_timeout_minutes?: number;
        };
        SettingsUpdateResponse: {
            success?: boolean;
            message?: string;
        };
        TelegramTrail: {
            message_id?: number | null;
            topic_id?: number | null;
            chat_id?: string | null;
            telegram_link?: string | null;
            /** @enum {string|null} */
            delivery_status?: "sent" | "failed" | "pending" | null;
            /** Format: date-time */
            delivered_at?: string | null;
        };
        TelegramHealthResponse: {
            /** @enum {string} */
            status?: "ok" | "degraded" | "error";
            webhook_alive?: boolean;
            /** Format: date-time */
            last_success_at?: string | null;
            /** Format: date-time */
            last_error_at?: string | null;
            last_error_message?: string | null;
            error_rate_24h?: number;
            pending_messages?: number;
        };
        TelegramVerifyRequest: {
            /**
             * @default client
             * @enum {string}
             */
            scope: "client" | "branch";
            /** Format: uuid */
            branch_id?: string | null;
            chat_id?: string | null;
        };
        TelegramVerifyResponse: {
            success?: boolean;
            /** @enum {string} */
            delivery_status?: "sent" | "failed";
            verification_code?: string;
            message_id?: number | null;
            chat_id?: string | null;
            /** Format: uuid */
            branch_id?: string | null;
            error_message?: string | null;
        };
        TelegramTestRequest: {
            /**
             * @default client
             * @enum {string}
             */
            scope: "client" | "branch";
            /** Format: uuid */
            branch_id?: string | null;
            chat_id?: string | null;
            message?: string | null;
        };
        TelegramTestResponse: {
            success?: boolean;
            /** @enum {string} */
            delivery_status?: "sent" | "failed";
            message_id?: number | null;
            chat_id?: string | null;
            /** Format: uuid */
            branch_id?: string | null;
            error_message?: string | null;
        };
        TelegramLinkResponse: {
            token?: string;
            deep_link?: string | null;
            bot_username?: string | null;
            /** Format: date-time */
            expires_at?: string;
        };
        BookingCreate: {
            /** Format: uuid */
            specialist_id: string;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            customer_name?: string | null;
            customer_phone?: string | null;
            service_type?: string | null;
            notes?: string | null;
            /** Format: uuid */
            conversation_id?: string | null;
        };
        BookingResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            specialist_id: string;
            specialist_name: string;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
            customer_name?: string | null;
            customer_phone?: string | null;
            service_type?: string | null;
            status: string;
            google_event_id?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        BookingActionResponse: {
            success: boolean;
            booking: components["schemas"]["BookingResponse"];
        };
        BookingsListResponse: {
            items: components["schemas"]["BookingResponse"][];
        };
        SlotResponse: {
            start?: string;
            end?: string;
            start_time?: string;
            end_time?: string;
            available?: boolean;
        };
        SlotsResponse: {
            date?: string;
            /** Format: uuid */
            specialist_id?: string;
            specialist_name?: string;
            duration_minutes?: number;
            slots?: components["schemas"]["SlotResponse"][];
        };
        SpecialistResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uuid */
            branch_id?: string | null;
            branch_name?: string | null;
            services?: Record<string, never>[];
            is_active?: boolean;
        };
        SpecialistsResponse: {
            items?: components["schemas"]["SpecialistResponse"][];
        };
        GoogleStatusResponse: {
            connected: boolean;
            /** Format: date-time */
            expires_at?: string | null;
            is_expired: boolean;
        };
        AuditEvent: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            event_type?: string;
            actor_name?: string | null;
            entity_type?: string | null;
            /** Format: uuid */
            entity_id?: string | null;
            payload?: Record<string, never> | null;
        };
        AuditListResponse: {
            items?: components["schemas"]["AuditEvent"][];
            cursor?: string | null;
            has_more?: boolean;
        };
    };
    responses: {
        /** @description Missing or invalid auth token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "AUTH_REQUIRED",
                 *         "message": "Authentication required",
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INVALID_PARAM",
                 *         "message": "Invalid parameter",
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "ACCESS_DENIED",
                 *         "message": "You do not have permission to perform this action",
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "Case not found",
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Case already assigned to another agent */
        CaseAlreadyTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "CASE_ALREADY_TAKEN",
                 *         "message": "Case is already assigned to another agent",
                 *         "details": {
                 *           "assigned_to": "John Doe"
                 *         },
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Case not assigned to current agent */
        NotAssigned: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_ASSIGNED",
                 *         "message": "You must take the case before performing this action",
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Idempotency key already used or in progress */
        IdempotencyConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "IDEMPOTENCY_CONFLICT",
                 *         "message": "Request already processed",
                 *         "trace_id": "abc123"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation error */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ValidationError"];
            };
        };
    };
    parameters: {
        /** @description Stable key for safe retries of mutating requests. */
        idempotency_key: string;
        /** @description Client selection when identity maps to multiple clients. */
        client_id_header: string;
        /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
        branch_id_header: string;
        /** @example 39af8e47-a062-4b81-8343-34bdc3084ef9 */
        case_id: string;
        /** @example f0b1a4c7-8f33-4f92-9b1f-9fe0f3d3e7b1 */
        agent_id: string;
        /** @description Pagination cursor (opaque) */
        cursor: string;
        limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    linkAgentTelegram: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path: {
                /** @example f0b1a4c7-8f33-4f92-9b1f-9fe0f3d3e7b1 */
                agent_id: components["parameters"]["agent_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramLinkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCases: {
        parameters: {
            query?: {
                status?: "pending" | "active" | "resolved";
                branch_id?: string;
                assigned_to_me?: boolean;
                date_from?: string;
                date_to?: string;
                /** @description Pagination cursor (opaque) */
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path: {
                /** @example 39af8e47-a062-4b81-8343-34bdc3084ef9 */
                case_id: components["parameters"]["case_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    takeCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
                /** @description Stable key for safe retries of mutating requests. */
                "Idempotency-Key"?: components["parameters"]["idempotency_key"];
            };
            path: {
                /** @example 39af8e47-a062-4b81-8343-34bdc3084ef9 */
                case_id: components["parameters"]["case_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case taken successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseActionResponse"];
                };
            };
            /** @description Case already taken or idempotency key conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    resolveCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
                /** @description Stable key for safe retries of mutating requests. */
                "Idempotency-Key"?: components["parameters"]["idempotency_key"];
            };
            path: {
                /** @example 39af8e47-a062-4b81-8343-34bdc3084ef9 */
                case_id: components["parameters"]["case_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseActionResponse"];
                };
            };
            403: components["responses"]["NotAssigned"];
            409: components["responses"]["IdempotencyConflict"];
        };
    };
    returnCase: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
                /** @description Stable key for safe retries of mutating requests. */
                "Idempotency-Key"?: components["parameters"]["idempotency_key"];
            };
            path: {
                /** @example 39af8e47-a062-4b81-8343-34bdc3084ef9 */
                case_id: components["parameters"]["case_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Case returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseActionResponse"];
                };
            };
            403: components["responses"]["NotAssigned"];
            409: components["responses"]["IdempotencyConflict"];
        };
    };
    getCaseMessages: {
        parameters: {
            query?: {
                /** @description Pagination cursor (opaque) */
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path: {
                /** @example 39af8e47-a062-4b81-8343-34bdc3084ef9 */
                case_id: components["parameters"]["case_id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    sendManagerMessage: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
                /** @description Stable key for safe retries of mutating requests. */
                "Idempotency-Key"?: components["parameters"]["idempotency_key"];
            };
            path: {
                /** @example e03933eb-780e-4d0d-890f-741bc3ca9733 */
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Message queued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            403: components["responses"]["NotAssigned"];
            409: components["responses"]["IdempotencyConflict"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMetricsDaily: {
        parameters: {
            query?: {
                /** @description Defaults to today */
                date?: string;
            };
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsDailyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getTelegramHealth: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telegram health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramHealthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    verifyTelegramConnector: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramVerifyRequest"];
            };
        };
        responses: {
            /** @description Verification message result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramVerifyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    sendTelegramTest: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramTestRequest"];
            };
        };
        responses: {
            /** @description Test message result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramTestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsUpdateResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                entity_type?: "case" | "conversation" | "settings" | "agent" | "branch" | "client" | "integration";
                entity_id?: string;
                /** @description Pagination cursor (opaque) */
                cursor?: components["parameters"]["cursor"];
                limit?: components["parameters"]["limit"];
            };
            header?: {
                /** @description Client selection when identity maps to multiple clients. */
                "X-Client-Id"?: components["parameters"]["client_id_header"];
                /** @description Branch selection when identity is branch-scoped or multiple branches exist. */
                "X-Branch-Id"?: components["parameters"]["branch_id_header"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
}
