"""Explicit demo_salon pack adapter."""

from __future__ import annotations

from app.services.demo_salon_knowledge import (
    _build_fact_meta,
    _pack_query_phrase_intents,
    _resolve_pack_query_price_item,
    _build_pack_query_price_reply,
    _pack_query_question_classifier,
    _build_pack_query_service_decision,
    _resolve_pack_query_service_hint,
    _resolve_pack_query_semantic_match,
    _build_pack_query_truth_decision,
    _detect_promotion_intent,
    _find_best_price_item,
    _format_price_reply,
    _format_service_duration_reply,
    _format_service_not_found_reply,
    _format_service_presence_reply_for_name,
    _format_service_reply,
    _has_contact_signal,
    _has_duration_signal,
    _has_guest_waiting_signal,
    _has_parking_signal,
    _has_price_signal,
    _match_service,
    _matches_service_request_lexicon,
    _normalize_client_slug,
    _normalize_text,
    build_evening_greeting,
    build_info_combined_reply,
    build_quiet_hours_notice,
    compose_multi_truth_reply,
    format_reply_from_truth,
    get_signal_lexicon_list,
    get_system_anchor_groups,
    get_system_lexicon_list,
    load_policy_pack,
    load_system_lexicons,
    load_yaml_truth,
)


_COMPAT_EXPORTS = [
    "_pack_query_phrase_intents",
    "_resolve_pack_query_price_item",
    "_build_pack_query_price_reply",
    "_pack_query_question_classifier",
    "_build_pack_query_service_decision",
    "_resolve_pack_query_service_hint",
    "_resolve_pack_query_semantic_match",
    "_build_pack_query_truth_decision",
]

__all__ = [
    "_build_fact_meta",
    "_has_contact_signal",
    "_detect_promotion_intent",
    "_find_best_price_item",
    "_format_price_reply",
    "_format_service_duration_reply",
    "_format_service_presence_reply_for_name",
    "_format_service_reply",
    "_format_service_not_found_reply",
    "_has_guest_waiting_signal",
    "_has_duration_signal",
    "_has_parking_signal",
    "_has_price_signal",
    "_match_service",
    "_matches_service_request_lexicon",
    "_normalize_client_slug",
    "_normalize_text",
    "build_evening_greeting",
    "build_info_combined_reply",
    "build_quiet_hours_notice",
    "compose_multi_truth_reply",
    "format_reply_from_truth",
    "get_signal_lexicon_list",
    "get_system_anchor_groups",
    "get_system_lexicon_list",
    "load_policy_pack",
    "load_system_lexicons",
    "load_yaml_truth",
]
