"""Legacy webhook adapter: re-export decision orchestrator symbols."""

from __future__ import annotations

from app.routers.webhook.context_manager import _apply_consult_return
from app.routers.webhook.response import _apply_quiet_hours_notice, _maybe_append_booking_cta
from app.routers.webhook.runtime_primitives import (
    BOOKING_CTA_SERVICE_INTENTS,
    BOOKING_TIME_SERVICE_INTENTS,
    EXPECTED_REPLY_INTENT_CHOICE,
    EXPECTED_REPLY_NAME,
    EXPECTED_REPLY_PHONE,
    EXPECTED_REPLY_SERVICE,
    EXPECTED_REPLY_TIME,
    INFO_ANCHOR_GROUPS,
    INFO_INTENT_PRIORITY_GENERIC,
    INFO_INTENT_PRIORITY_SERVICE,
    INFO_INTENTS,
    INFO_NON_SERVICE_INTENTS,
    INFO_SERVICE_DEPENDENT_INTENTS,
    MSG_AI_ERROR,
    MSG_BOOKING_ASK_DATETIME,
    MSG_BOOKING_ASK_NAME,
    MSG_BOOKING_PENDING_QUESTION_TIME_GUIDANCE,
    MSG_BOOKING_SPECIALIST_AVAILABILITY_FOLLOWUP,
    MSG_BOOKING_ASK_SERVICE,
    MSG_BOOKING_CTA,
    MSG_DELIVERY_FAILED,
    MSG_EXPECTED_SERVICE_OFF_TOPIC,
    QUESTION_WORD_PREFIXES,
    SERVICE_CARRYOVER_TTL_MESSAGES,
    SESSION_MEMORY_SHORT_TOKENS,
    ConversationState,
)
from app.services.chatflow_service import send_bot_response

from . import decision as _decision

_SHARED_EXPORTS = {
    "BOOKING_CTA_SERVICE_INTENTS": BOOKING_CTA_SERVICE_INTENTS,
    "BOOKING_TIME_SERVICE_INTENTS": BOOKING_TIME_SERVICE_INTENTS,
    "ConversationState": ConversationState,
    "EXPECTED_REPLY_INTENT_CHOICE": EXPECTED_REPLY_INTENT_CHOICE,
    "EXPECTED_REPLY_NAME": EXPECTED_REPLY_NAME,
    "EXPECTED_REPLY_PHONE": EXPECTED_REPLY_PHONE,
    "EXPECTED_REPLY_SERVICE": EXPECTED_REPLY_SERVICE,
    "EXPECTED_REPLY_TIME": EXPECTED_REPLY_TIME,
    "INFO_ANCHOR_GROUPS": INFO_ANCHOR_GROUPS,
    "INFO_INTENTS": INFO_INTENTS,
    "INFO_INTENT_PRIORITY_GENERIC": INFO_INTENT_PRIORITY_GENERIC,
    "INFO_INTENT_PRIORITY_SERVICE": INFO_INTENT_PRIORITY_SERVICE,
    "INFO_NON_SERVICE_INTENTS": INFO_NON_SERVICE_INTENTS,
    "INFO_SERVICE_DEPENDENT_INTENTS": INFO_SERVICE_DEPENDENT_INTENTS,
    "MSG_AI_ERROR": MSG_AI_ERROR,
    "MSG_BOOKING_ASK_DATETIME": MSG_BOOKING_ASK_DATETIME,
    "MSG_BOOKING_ASK_NAME": MSG_BOOKING_ASK_NAME,
    "MSG_BOOKING_PENDING_QUESTION_TIME_GUIDANCE": MSG_BOOKING_PENDING_QUESTION_TIME_GUIDANCE,
    "MSG_BOOKING_SPECIALIST_AVAILABILITY_FOLLOWUP": MSG_BOOKING_SPECIALIST_AVAILABILITY_FOLLOWUP,
    "MSG_BOOKING_ASK_SERVICE": MSG_BOOKING_ASK_SERVICE,
    "MSG_BOOKING_CTA": MSG_BOOKING_CTA,
    "MSG_DELIVERY_FAILED": MSG_DELIVERY_FAILED,
    "MSG_EXPECTED_SERVICE_OFF_TOPIC": MSG_EXPECTED_SERVICE_OFF_TOPIC,
    "QUESTION_WORD_PREFIXES": QUESTION_WORD_PREFIXES,
    "SERVICE_CARRYOVER_TTL_MESSAGES": SERVICE_CARRYOVER_TTL_MESSAGES,
    "SESSION_MEMORY_SHORT_TOKENS": SESSION_MEMORY_SHORT_TOKENS,
}

globals().update(_SHARED_EXPORTS)

for _name, _value in _decision.__dict__.items():
    if _name.startswith("__") or _name in _SHARED_EXPORTS:
        continue
    globals()[_name] = _value

del _decision
del _SHARED_EXPORTS

__all__ = [name for name in globals() if not name.startswith("__")]
